[project]
name = "convstr"
version = "0.1.0"
description = "Fetch and cache conversations"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "neo4j>=5.28.1",
    "pandas>=2.2.3",
    "pandas-stubs>=2.2.3.250308",
]
