"""
This type stub file was generated by pyright.
"""

import logging
import neo4j
from typing import LiteralString

query: LiteralString = ...
def get_conversations(logger: logging.Logger) -> list[neo4j.Record]:
    ...

def run_query(driver: neo4j.Driver, query: LiteralString, logger: logging.Logger) -> list[neo4j.Record]:
    ...

