"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, NotRequired, TypedDict
from datetime import date
from neo4j import Record

@dataclass
class Tweet:
    id: str
    text: str
    sentiment_label: str
    sentiment_score: float
    created_at: date
    negative: float
    neutral: float
    positive: float
    reply_to: str | None = ...


class TweetData(TypedDict):
    id: str
    text: str
    sentiment_label: str
    sentiment_score: float
    created_at: date
    negative: float
    neutral: float
    positive: float
    reply_to: NotRequired[str]
    ...


def make_tweet(data: TweetData) -> Tweet:
    ...

def filter_to_tweet_fields(data: dict[Any, Any]) -> dict[str, Any]:
    ...

def make_conversation(record: Record) -> list[Tweet]:
    ...

