"""
This type stub file was generated by pyright.
"""

import logging
import pandas as pd
from .tweet import Tweet

def main(): # -> None:
    ...

def parse_to_df(conversations: list[list[Tweet]]) -> pd.DataFrame:
    ...

def load_conversations(logger: logging.Logger) -> None:
    ...

def create_logger() -> logging.Logger:
    ...

if __name__ == "__main__":
    ...
